before:
  hooks:
    - go mod tidy
    - make ui/build
builds:
  - main: ./cmd/parca/
    id: "parca"
    binary: parca
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -v
    ldflags:
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
    targets:
      - go_first_class
      - go_118_first_class
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
source:
  enabled: true
release:
  prerelease: auto
  # Defaults to empty.
  footer: |
    ## Docker images

    `docker pull ghcr.io/parca-dev/parca:{{ .Tag }}`

    ## Thanks!

    Join our [Discord server](https://discord.com/invite/ZgUpYgpzXy);
    Follow us on [Twitter](https://twitter.com/ParcaDev);
    Read the [documentation](https://www.parca.dev/docs/overview).
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# It's still not possible to use docker (buildx) for reproducible builds.
# And Goreleaser only supports podman with pro version, (https://goreleaser.com/customization/docker/#podman)
# for full build pipeline transparency, we don't want to use pro version for Parca.

#dockers:
#  # https://goreleaser.com/customization/docker/
#  - id: amd64
#    use: buildx
#    image_templates:
#      - parca-dev/{{ .ProjectName }}:{{ .Version }}-amd64
#      - parca-dev/{{ .ProjectName }}:latest-amd64
#    dockerfile: Dockerfile
#    extra_files:
#      - parca.yaml
#    build_flag_templates:
#      - --platform=linux/amd64
#      - --label=org.opencontainers.image.title={{ .ProjectName }}
#      - --label=org.opencontainers.image.description={{ .ProjectName }}
#      - --label=org.opencontainers.image.url=https://github.com/parca-dev/{{ .ProjectName }}
#      - --label=org.opencontainers.image.source=https://github.com/parca-dev/{{ .ProjectName }}
#      - --label=org.opencontainers.image.created={{.CommitDate}}
#      - --label=org.opencontainers.image.version={{ .Version }}
#      - --label=org.opencontainers.image.revision={{ .FullCommit }}
#      - --label=org.opencontainers.image.licenses=Apache-2.0
#
#  - id: arm64
#    use: buildx
#    image_templates:
#      - parca-dev/{{ .ProjectName }}:{{ .Version }}-arm64v8
#      - parca-dev/{{ .ProjectName }}:latest-arm64v8
#    goarch: arm64
#    dockerfile: Dockerfile
#    extra_files:
#      - parca.yaml
#    build_flag_templates:
#      - --platform=linux/arm64/v8
#      - --label=org.opencontainers.image.title={{ .ProjectName }}
#      - --label=org.opencontainers.image.description={{ .ProjectName }}
#      - --label=org.opencontainers.image.url=https://github.com/parca-dev/{{ .ProjectName }}
#      - --label=org.opencontainers.image.source=https://github.com/parca-dev/{{ .ProjectName }}
#      - --label=org.opencontainers.image.version={{ .Version }}
#      - --label=org.opencontainers.image.created={{.CommitDate}}
#      - --label=org.opencontainers.image.revision={{ .FullCommit }}
#      - --label=org.opencontainers.image.licenses=Apache-2.0
