FROM node:17.3.0-alpine3.14 AS ui-deps

WORKDIR /app

COPY ui/packages/shared ./packages/shared
COPY ui/packages/app/web/package.json ./packages/app/web/package.json
COPY ui/package.json ui/yarn.lock ./
RUN yarn workspace @parca/web install --frozen-lockfile

FROM node:17.3.0-alpine3.14 AS ui-builder

WORKDIR /app

COPY ui .
COPY --from=ui-deps /app/node_modules ./node_modules
RUN yarn workspace @parca/web build

FROM golang:1.17.6-alpine AS builder

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.7.2
RUN go install github.com/grpc-ecosystem/grpc-health-probe@latest

COPY go.mod go.sum /app/
RUN go mod download -modcacherw

COPY ./ui/ui.go ./ui/ui.go
COPY --from=ui-builder /app/packages/app/web/dist ./ui/packages/app/web/dist

COPY ./cmd /app/cmd
COPY ./pkg /app/pkg
COPY ./internal /app/internal
COPY ./proto /app/proto
COPY ./gen /app/gen

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -gcflags="all=-N -l" -o parca ./cmd/parca

FROM golang:1.17.6-alpine

COPY --from=builder /go/bin/dlv /
COPY --from=builder /go/bin/grpc-health-probe /
COPY --from=builder /app/parca /parca
COPY parca.yaml /parca.yaml

EXPOSE 7070

ENTRYPOINT ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "--continue", "--"]
