# this image is what docker.io/alpine:3.14.1 on August 13 2021
FROM docker.io/alpine@sha256:be9bdc0ef8e96dbc428dc189b31e2e3b05523d96d12ed627c37aa2936653258c
RUN apk add --no-cache llvm
USER nobody

COPY --chown=0:0 parca.yaml /
COPY --chown=0:0 parca /

CMD ["/parca"]
