# Designed to only used by Tilt to iterate faster on the API.
FROM golang:1.17.6-alpine AS builder

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.7.2
RUN go install github.com/grpc-ecosystem/grpc-health-probe@latest

COPY go.mod go.sum /app/
RUN go mod download -modcacherw

# Create a dummy ui package to convience go compiler.
RUN mkdir -p /app/ui/packages/app/web/dist && \
    touch /app/ui/packages/app/web/dist/index.html && \
    echo $'package ui\n \
    import "embed"\n\
    //go:embed packages/app/web/dist\n\
    var FS embed.FS\n'\
    > ./ui/ui.go

COPY ./cmd /app/cmd
COPY ./pkg /app/pkg
COPY ./internal /app/internal
COPY ./proto /app/proto
COPY ./gen /app/gen

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -gcflags="all=-N -l" -o parca ./cmd/parca

FROM golang:1.17.6-alpine

COPY --from=builder /go/bin/dlv /
COPY --from=builder /go/bin/grpc-health-probe /
COPY --from=builder /app/parca /parca
COPY parca.yaml /parca.yaml

EXPOSE 7070

ENTRYPOINT ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "--continue", "--"]
