// @generated by protoc-gen-connect-web v0.8.4 with parameter "target=ts"
// @generated from file parca/profilestore/v1alpha1/profilestore.proto (package parca.profilestore.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentsRequest, AgentsResponse, WriteRawRequest, WriteRawResponse } from "./profilestore_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ProfileStoreService is the service the accepts pprof writes
 *
 * @generated from service parca.profilestore.v1alpha1.ProfileStoreService
 */
export const ProfileStoreService = {
  typeName: "parca.profilestore.v1alpha1.ProfileStoreService",
  methods: {
    /**
     * WriteRaw accepts a raw set of bytes of a pprof file
     *
     * @generated from rpc parca.profilestore.v1alpha1.ProfileStoreService.WriteRaw
     */
    writeRaw: {
      name: "WriteRaw",
      I: WriteRawRequest,
      O: WriteRawResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * AgentsService maintains the agents
 *
 * @generated from service parca.profilestore.v1alpha1.AgentsService
 */
export const AgentsService = {
  typeName: "parca.profilestore.v1alpha1.AgentsService",
  methods: {
    /**
     * Agents return the agents that pushed data to the server
     *
     * @generated from rpc parca.profilestore.v1alpha1.AgentsService.Agents
     */
    agents: {
      name: "Agents",
      I: AgentsRequest,
      O: AgentsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

