# vim: ft=dockerfile
FROM docker.io/node:16.20.1-alpine@sha256:82b203db6fb3500464df249b28eb497f9fb28ca41c1800d792ad4ab75445a29e
WORKDIR /app

COPY package.json yarn.lock ./
# hadolint ignore=DL3060
RUN yarn install --frozen-lockfile

COPY . .
# hadolint ignore=DL3060
RUN yarn workspace @parca/web install

EXPOSE 3000

CMD ["yarn", "workspace", "@parca/web", "dev"]
