# vim: ft=dockerfile
FROM docker.io/node:16.20.1-alpine@sha256:e5973154d5943265bdcd803f4b769db84b38ac35c1e235f1bb2afcbb4a743740
WORKDIR /app

COPY package.json yarn.lock ./
# hadolint ignore=DL3060
RUN yarn install --frozen-lockfile

COPY . .
# hadolint ignore=DL3060
RUN yarn workspace @parca/web install

EXPOSE 3000

CMD ["yarn", "workspace", "@parca/web", "dev"]
