# vim: ft=dockerfile
FROM docker.io/node:16.20.0-alpine@sha256:8d0dcbf89ad1a5bc561dd0725a6529c98f83065ba6cdd14e69bc5cc7ac565565
WORKDIR /app

COPY package.json yarn.lock ./
# hadolint ignore=DL3060
RUN yarn install --frozen-lockfile

COPY . .
# hadolint ignore=DL3060
RUN yarn workspace @parca/web install

EXPOSE 3000

CMD ["yarn", "workspace", "@parca/web", "dev"]
